// This file is @generated by prost-build.
/// Control file to link operation to index segments.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SegmentControl {
    /// Hash (or file name) of the commit index segment.
    #[prost(bytes = "vec", tag = "1")]
    pub commit_segment_id: ::prost::alloc::vec::Vec<u8>,
}
